rapidsai/wholegraph

- .github/ops-bot.yaml
- .github/workflows/build.yaml
Fix syntax error in `build.yaml`.
> Correct syntax in GHA workflow

- ci/test_wheel.sh
This PR is to fix wheel-test in CI.
@chuangz0 also helped find the root course:
Pytorch cu121 nightly seems will initialize CUDA at import time, which will cause later forked subprocess failed in CUDA calls.
Fix:
Change pytorch cu121 back to stable.
> change pytorch cu121 to stable to fix ci

- ci/test_wheel.sh
Forward-merge triggered by push to `branch-23.12` that creates a PR to keep `branch-24.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.12 to branch-24.02

- python/pylibwholegraph/examples/node_classfication.py
- python/pylibwholegraph/pylibwholegraph/torch/common_options.py
- python/pylibwholegraph/pylibwholegraph/torch/distributed_launch.py
- python/pylibwholegraph/pylibwholegraph/torch/gnn_model.py
replace `optparse`  with `argparser` in `pylibwholegraph`
> replace optparse  with argparser

- cpp/src/wholememory/memory_handle.cpp
move_vector_clear_outside_loop in memory_handle.cpp
> move_vector_clear_outside_loop

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-120_arch-x86_64.yaml
- dependencies.yaml
- python/pylibwholegraph/pyproject.toml
This PR aligns versions for wholegraph dependencies with versions used by other RAPIDS packages. This is needed for devcontainers, to make the unified RAPIDS conda environment solvable. See https://github.com/rapidsai/devcontainers/pull/191.
> Align versions for cudnn, clang-tools, cython, and doxygen with the rest of RAPIDS.

- python/pylibwholegraph/CMakeLists.txt
This change allows standard CMake specification of the C++ package directory (via `-Dwholegraph_ROOT`) to also work during the Python build.
> Don't overwrite wholegraph_ROOT if provided

- .pre-commit-config.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- dependencies.yaml
Contributes to https://github.com/rapidsai/build-planning/issues/7.
Proposes splitting the `cuda-version` dependency in `dependencies.yaml` out to its own thing, separate from the bits of the CUDA Toolkit this project needs.
* prevents accidental inclusion of multiple `cuda-version` version in environments
* reduces update effort (via enabling more use of globs like `"12.*"`)
* improves the chance that errors like "`conda` recipe is missing a dependency" are caught in CI
This change was intended to just re-organize `dependencies.yaml`, but I do think the one additional change it introduces to `all_cuda-118_arch-x86_64.yaml` is a good one. I *think* requiring the `cuda-version` metapackage in all environments is useful to prevent against environment solves that result in runtime issues. …
> refactor CUDA versions in dependencies.yaml

- cpp/src/wholememory_ops/functions/nvshmem_device_reference.cuh
- cpp/src/wholememory_ops/gather_op_impl_nvshmem.cu
- python/pylibwholegraph/pylibwholegraph/torch/common_options.py
> fix inferencesample option

- cpp/src/wholememory_ops/functions/embedding_optimizer_func.cu
- cpp/tests/wholememory_ops/wholememory_embedding_gradient_apply_tests.cu
Fix a bug for embedding optimizer, it leads to undefined behavior when embedding_dim is not multiple of 32.
> fix a bug for embedding optimizer, which leads to undefined behavior

- cpp/src/wholememory_ops/functions/embedding_optimizer_func.cu
- cpp/src/wholememory_ops/functions/nvshmem_device_reference.cuh
- cpp/src/wholememory_ops/gather_op_impl_nvshmem.cu
- cpp/tests/wholememory_ops/wholememory_embedding_gradient_apply_tests.cu
- python/pylibwholegraph/pylibwholegraph/torch/common_options.py
Forward-merge triggered by push to `branch-24.02` that creates a PR to keep `branch-24.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-24.02 to branch-24.04

- python/pylibwholegraph/pylibwholegraph/torch/comm.py
- python/pylibwholegraph/pylibwholegraph/torch/initialize.py
This PR is to address https://github.com/rapidsai/wholegraph/issues/110. 
Please feel free to comment and suggest here.
> Reset WholeGraph communicators during the finalize call

- .gitignore
- dependencies.yaml
Move conda-only dependencies out of `pyproject` and `requirements` sections in `dependencies.yaml`.
> Fix pip dependencies

- python/pylibwholegraph/setup.py
This reverts commit 503cdcd1e6f38000967b60de59bd811c379c523c.
This change introduced [test errors](https://github.com/rapidsai/wholegraph/actions/runs/7827336502/job/21354958620), so reverting for `24.02` and will fix in `24.04` (in #128 most likely).
> Revert "Exclude tests from builds (#127)"

- cpp/include/wholememory/wholememory.h
- cpp/src/wholememory/initialize.cpp
- cpp/src/wholememory/initialize.hpp
- cpp/src/wholememory/wholememory.cpp
- python/pylibwholegraph/examples/node_classfication.py
- python/pylibwholegraph/pylibwholegraph/binding/wholememory_binding.pyx
- python/pylibwholegraph/pylibwholegraph/torch/common_options.py
- python/pylibwholegraph/pylibwholegraph/torch/initialize.py
Add log-level-control interface in pylibwholegraph to allow user to control log level in wholememory.
> Logging level

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-122_arch-x86_64.yaml
- dependencies.yaml
- python/pylibwholegraph/pyproject.toml
Contributes to https://github.com/rapidsai/build-planning/issues/3
This PR adds support for Python 3.11.
It also bumps uses of `NumPy` to `numpy>=1.23`, see https://github.com/rapidsai/build-planning/issues/3#issuecomment-1967952280.
This is part of ongoing work to add Python 3.11 support across RAPIDS.
The Python 3.11 CI workflows introduced in https://github.com/rapidsai/shared-workflows/pull/176 are *optional*... they are not yet required to run successfully for PRs to be merged.
This PR can be merged once all jobs are running successfully (including the non-required jobs for Python 3.11). The CI logs should be verified that the jobs are building and testing with Python 3.11.
See https://github.com/rapidsai/shared-workflows/pull/176 for more details.
> Add support for Python 3.11, require NumPy 1.23+

- cpp/CMakeLists.txt
- python/pylibwholegraph/CMakeLists.txt
CMake [initializes `CMAKE_CUDA_ARCHITECTURES` from the `CUDAARCHS` environment variable](https://cmake.org/cmake/help/latest/variable/CMAKE_CUDA_ARCHITECTURES.html).
Defaulting `CMAKE_CUDA_ARCHITECTURES` to a fixed list of archs prevents CMake from initializing the value from the envvar.
This PR skips setting `CMAKE_CUDA_ARCHITECTURES`, and instead uses `rapids-cmake` default behavior of [initializing from the `CUDAARCHS` envvar](https://github.com/rapidsai/rapids-cmake/blob/branch-24.04/rapids-cmake/cuda/init_architectures.cmake#L73-L93) and falling back to the same default [archs list](https://github.com/rapidsai/rapids-cmake/blob/branch-24.04/rapids-cmake/cuda/set_architectures.cmake#L54) as is currently used in `build.sh`.
> Use default `rapids-cmake` CUDA_ARCHITECTURES

- cpp/src/wholememory_ops/functions/exchange_embeddings_nccl_func.cu
Remove an unnecessary sync, which may lead to bad overlapping performance.
> remove an unnecessary sync in exchange_embeddings_nccl_func

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-122_arch-x86_64.yaml
- dependencies.yaml
NumPy 2 is expected to be released in the near future. For the RAPIDS 24.04 release, we will pin to `numpy>=1.23,<2.0a0`. This PR adds an upper bound to affected RAPIDS repositories.
xref: https://github.com/rapidsai/build-planning/issues/29
> Add upper bound to prevent usage of NumPy 2

- .github/workflows/build.yaml
This PR updates the script inputs in the relevant workflows from `build_script` and `test_script` to `script`. 
Depends on https://github.com/rapidsai/shared-workflows/pull/191
> Update script input name

- ci/build_docs.sh
- ci/check_style.sh
- ci/test_clang_tidy.sh
- ci/test_cpp.sh
- ci/test_python.sh
conda dropped support for the `--force` flag to `conda env create`. This changes that flag name to `--yes`.
See https://github.com/conda/conda/blob/main/CHANGELOG.md#2430-2024-03-12 and https://github.com/rapidsai/miniforge-cuda/pull/63 for more info.
> Use `conda env create --yes` instead of `--force`

- ci/test_python.sh
mkl2024.1.0 conflicts with pytorch, this PR constrains mkl<2024.1.0 in the test scripts where pytorch is required.
> fix CI issue due to pytorch and mkl version conflict

- ci/test_python.sh
- cpp/src/graph_ops/append_unique_func.cuh
- cpp/src/wholegraph_ops/unweighted_sample_without_replacement_func.cuh
- cpp/src/wholegraph_ops/weighted_sample_without_replacement_func.cuh
- cpp/src/wholememory_ops/functions/exchange_embeddings_nccl_func.cu
- cpp/src/wholememory_ops/functions/exchange_ids_nccl_func.cu
- cpp/src/wholememory_ops/functions/nvshmem_gather_scatter_func.cuh
fix to issue 148[https://github.com/rapidsai/wholegraph/issues/148](url), remove unnecessary sync between thrust ops and host cpu threads
> remove unnecessary sync between thrust ops and host threads

- ci/test_python.sh
- cpp/src/wholememory_ops/temp_memory_handle.hpp
- python/pylibwholegraph/pylibwholegraph/torch/wholegraph_env.py
- python/pylibwholegraph/pylibwholegraph/torch_cpp_ext/torch_env_func_ptrs.cpp
- python/pylibwholegraph/pylibwholegraph/torch_cpp_ext/wholegraph_torch_ext.cpp
fix to[ issue 76](https://github.com/rapidsai/wholegraph/issues/76), which allows temp_memory_handler to allocate memory for multiple times.
> allow temp_memory_handler to allocate memory for multiple times

- cpp/src/wholememory/file_io.cpp
- cpp/src/wholememory_ops/functions/map_indices_func.cu
- python/pylibwholegraph/pylibwholegraph/torch/embedding.py
- python/pylibwholegraph/pylibwholegraph/torch/tensor.py
quick fix to a map_indice bug && add comment for parameter round_robin_size
> quick fix to a map_indice bug && add comment for parameter round_robin_size

- python/pylibwholegraph/pylibwholegraph/torch/tensor.py
A quick fixes to this issue (https://github.com/rapidsai/wholegraph/issues/168). Set correct default wholememory tensor gather results data type.
> a quick fix to wholememory tensor gather default data type

- cpp/src/wholememory_ops/functions/gather_func.cu
- cpp/src/wholememory_ops/functions/gather_func_impl_floating_data_int32_indices.cu
- cpp/src/wholememory_ops/functions/gather_func_impl_floating_data_int64_indices.cu
- cpp/src/wholememory_ops/functions/gather_func_impl_integer_data_int32_indices.cu
- cpp/src/wholememory_ops/functions/gather_func_impl_integer_data_int64_indices.cu
- cpp/src/wholememory_ops/functions/gather_scatter_func.cuh
- cpp/src/wholememory_ops/functions/gather_scatter_func.h
- cpp/src/wholememory_ops/functions/sort_indices_func.cu
- cpp/src/wholememory_ops/functions/sort_indices_func.h
- cpp/src/wholememory_ops/gather_op.cpp
- cpp/src/wholememory_ops/gather_op_impl.h
- cpp/src/wholememory_ops/gather_op_impl_mapped.cu
- cpp/tests/wholememory_ops/wholememory_gather_tests.cu
In continuous/chunked host mode, sorting indices before gathering can improve bandwidth by enhancing memory locality.
> Sort indices before gathering

- cpp/include/wholememory/embedding.h
- cpp/src/wholememory/embedding.cpp
- cpp/src/wholememory/embedding.hpp
- cpp/tests/wholememory_ops/wholememory_embedding_gradient_apply_tests.cu
- cpp/tests/wholememory_ops/wholememory_embedding_tests.cu
- python/pylibwholegraph/examples/node_classfication.py
- python/pylibwholegraph/pylibwholegraph/binding/wholememory_binding.pyx
- python/pylibwholegraph/pylibwholegraph/torch/embedding.py
This PR refactors the embedding creation interface, decoupling it from the optimizer dependency. Users now can designate the embeddings for optimization during optimizer initialization.
cpp:
```
wholememory_create_embedding(&wm_embedding, ...);
wholememory_create_embedding_optimizer(&optimizer, ...);
wholememory_embedding_set_optimizer(wm_embedding, optimizer);
```
python:
```
wm_embedding = wgth.create_embedding(...)
wm_optimizer = wgth.create_wholememory_optimizer(wm_embedding, "adam", {})
```
> decouple embedding creation from optimizer

- cpp/CMakeLists.txt
- cpp/include/wholememory/wholememory.h
- cpp/src/wholememory/communicator.cpp
- cpp/src/wholememory/communicator.hpp
- cpp/src/wholememory/memory_handle.cpp
- cpp/src/wholememory/nccl_comms.cpp
- cpp/src/wholememory/nccl_comms.hpp
- cpp/src/wholememory/system_info.cpp
- cpp/src/wholememory/system_info.hpp
- cpp/src/wholememory/wholememory.cpp
- python/pylibwholegraph/pylibwholegraph/binding/wholememory_binding.pyx
- python/pylibwholegraph/pylibwholegraph/torch/__init__.py
- python/pylibwholegraph/pylibwholegraph/torch/comm.py
support split comm and get_local_mnnvl_comm
split_comm
```
def split_communicator(comm: WholeMemoryCommunicator, color: int, key: int = 0):
"""Split Communicator.
Creates a set of new communicators from an existing one. Ranks which pass the same color value will be part of the
same group; color must be a non-negative value.
The value of key will determine the rank order, and the smaller key means the smaller rank in new communicator.
If keys are equal between ranks, then the rank in the original communicator will be used to order ranks.
"""
```
> Mnnvl with split comm

- cpp/src/wholememory/memory_handle.cpp
1. The default shm option is still SYSTEMV, but users can choose POSIX API through system env using `export WG_USE_POSIX_SHM=1`.
2. `unlink` shm files immediately after `shm_open` to avoid leftover memory in `/dev/shm` in case of a wholegraph crash.
> allow users to choose shm allocation method for chunked/continous host memory

- dependencies.yaml
This project has some dependencies in `dependencies.yaml` which are part of groups that have `output_types: requirements`, but which use version specifiers that aren't recognized by `pip`.
For example, the use of a secondary build component matching a build string (a conda-specific pattern):
https://github.com/rapidsai/wholegraph/blob/f85ee4356f2e3d42195a2e0a6c7f195154c47091/dependencies.yaml#L247
And the use of a single `=` pin (not recognized by `pip`)
https://github.com/rapidsai/wholegraph/blob/f85ee4356f2e3d42195a2e0a6c7f195154c47091/dependencies.yaml#L288
I believe these were intended to only affect `conda` outputs from `rapids-dependency-file-generator`. This marks them that way.
I discovered this while running the following `cuda11.8-pip` unified devcontainer from …
> clarify which dependencies in dependencies.yaml are conda-only

- conda/environments/all_cuda-125_arch-x86_64.yaml
- dependencies.yaml
This adds a missing dependency on `cuda-nvml-dev` in `dependencies.yaml`. See https://github.com/rapidsai/wholegraph/pull/191/files#r1687368784.
> Add cuda-nvml-dev to dependencies.yaml.

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- dependencies.yaml
- python/pylibwholegraph/pyproject.toml
Contributes to https://github.com/rapidsai/build-planning/issues/88
Finishes the work of dropping Python 3.9 support.
This project stopped building / testing against Python 3.9 as of https://github.com/rapidsai/shared-workflows/pull/235.
This PR updates configuration and docs to reflect that.
Checked that there were no remaining uses like this:
```shell
git grep -E '3\.9'
git grep '39'
git grep 'py39'
```
And similar for variations on Python 3.8 (to catch things that were missed the last time this was done).
> Drop Python 3.9 support

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- dependencies.yaml
This PR removes the NumPy<2 pin.  `wholegraph` does not appear to be a heavy user of NumPy or CuPy, so it should be fine to simply remove the pin.
For other RAPIDS projects with heavier dependency, CuPy 13.3.0 was required (just released) to have sufficient good CuPy/NumPy interoperability.
> Remove NumPy <2 pin

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- dependencies.yaml
- python/pylibwholegraph/pyproject.toml
Contributes to https://github.com/rapidsai/build-planning/issues/40
This PR adds support for Python 3.12.
This is part of ongoing work to add Python 3.12 support across RAPIDS.
It temporarily introduces a build/test matrix including Python 3.12, from https://github.com/rapidsai/shared-workflows/pull/213.
A follow-up PR will revert back to pointing at the `branch-24.10` branch of `shared-workflows` once all
RAPIDS repos have added Python 3.12 support.
CI here is expected to fail until all of this project's upstream dependencies support Python 3.12.
This can be merged whenever all CI jobs are passing.
> Add support for Python 3.12

- conda/recipes/pylibwholegraph/meta.yaml
Just adds the existing license to the `pylibwholegraph` conda recipe.
> Ensure pylibwholegraph conda packages have the license

- .github/workflows/pr.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/recipes/libwholegraph/conda_build_config.yaml
- dependencies.yaml
Contributes to https://github.com/rapidsai/build-planning/issues/102
Fixes #217
Temporarily added a CUDA 11.4.3 test job to CI here (the same specs as the failing nightly), by pointing at the branch from https://github.com/rapidsai/shared-workflows/pull/246.
Observed the exact same failures with CUDA 11.4 reported in https://github.com/rapidsai/build-planning/issues/102.
```text
...
+ nccl                     2.10.3.1  hcad2f07_0                  rapidsai-nightly     125MB
...
./WHOLEGRAPH_CSR_WEIGHTED_SAMPLE_WITHOUT_REPLACEMENT_TEST: symbol lookup error: /opt/conda/envs/test/bin/gtests/libwholegraph/../../../lib/libwholegraph.so: undefined symbol: ncclCommSplit
sh -c exec "$0" ./WHOLEMEMORY_HANDLE_TEST 
./WHOLEMEMORY_HANDLE_TEST: symbol lookup error: …
```
> bump NCCL floor to 2.18.1.1, relax PyTorch pin

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/recipes/libwholegraph/conda_build_config.yaml
- dependencies.yaml
Follow-up to #218 
This bumps the NCCL floor here slightly higher, to `>=2.19`. Part of a RAPIDS-wide update of that floor for the 24.10 release. See https://github.com/rapidsai/build-planning/issues/102#issuecomment-2375595743 for context.
cc @linhu-nv for awareness
> bump NCCL floor to 2.19

- cpp/include/wholememory/wholememory.h
- cpp/src/wholememory/communicator.cpp
- cpp/src/wholememory/communicator.hpp
- cpp/src/wholememory/embedding.cpp
- cpp/src/wholememory/memory_handle.cpp
- cpp/src/wholememory/memory_handle.hpp
- cpp/src/wholememory/wholememory.cpp
- cpp/src/wholememory_ops/functions/bucket_ids_for_hierarchy_func.cu
- cpp/src/wholememory_ops/functions/bucket_ids_for_hierarchy_func.h
- cpp/src/wholememory_ops/functions/sort_unique_ids_for_hierarchy_func.cu
- cpp/src/wholememory_ops/functions/sort_unique_ids_for_hierarchy_func.h
- cpp/src/wholememory_ops/functions/sort_unique_indices_func.cu
- cpp/src/wholememory_ops/functions/sort_unique_indices_func.h
- cpp/src/wholememory_ops/gather_op.cpp
- cpp/src/wholememory_ops/gather_op_impl.h
- cpp/src/wholememory_ops/gather_op_impl_hierarchy.cu
- cpp/tests/wholememory_ops/wholememory_gather_tests.cu
- python/pylibwholegraph/pylibwholegraph/binding/wholememory_binding.pyx
- python/pylibwholegraph/pylibwholegraph/test_utils/test_comm.py
- python/pylibwholegraph/pylibwholegraph/torch/common_options.py
- python/pylibwholegraph/pylibwholegraph/torch/embedding.py
- python/pylibwholegraph/pylibwholegraph/torch/utils.py
This PR adds a new memory type called Hierarchy, which exploits power-law degree distribution in graph to reduce inter-node communication.
1. Hierarchy WholeMemory has the same storage pattern as Distributed WholeMemory and only optimizes the gather function.
2. Hierarchy WholeMemory can achieve 1.5x-2.0x speedup in multi-node gather, compared with Distributed. 
3. For intra-node host memory location, Hierarchy can still achieve 1.5x-2.0x speedup.
> Add a new memory type: Hierarchy

- ci/build_docs.sh
- ci/build_python.sh
- ci/release/update-version.sh
- ci/test_cpp.sh
- ci/test_python.sh
- ci/test_wheel.sh
Contributes to https://github.com/rapidsai/build-planning/issues/106
Proposes specifying the RAPIDS version in `conda install` calls in CI that install CI artifacts, to reduce the risk of CI jobs picking up artifacts from other releases.
> make conda installations in CI stricter
